# Configurations
title:            EGP Playybook
longtitle:        The Playbook of Equitable Grading Practices
#author:           HE Tao
email:            edwards@cs.vt.edu
description: >
  The Playbook of Equitable Grading Practices, created by the corresponding
  working group of SIGCSE Virtual 2024, and associated with the
  CS Equitable Grading Practices project
  (https://cs-equitable-grading-practices.github.io/).

version:          0.0.1
gitbook_version:  3.2.3

url:              'https://cs-equitable-grading-practices.github.io'
baseurl:          '/playbook'
repository:       'https://github.com/cs-equitable-grading-practices/playbook'
repository_tree:  main
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                none

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
